### ISSUE TITLE
Puntuación

### ISSUE THREAD

**Issue by Afelipe-Ruiz** [sbohorquez/allsubsetcox#2]
En las diapositivas de Introducción a Series de Tiempo en el slide de Operadores de rezagos dice "L  es lo que en matemáticas es conocido como un operador. No es un parámetro o un número pero puede ser tratado como tal para operaciones algebraicas..."
Yo lo pondría como "L  es lo que en matemáticas es conocido como un operador. No es un parámetro o un número, pero puede ser tratado como tal para operaciones algebraicas, e.g.

**Comment by sbohorquez** [comment]
Hola, haré el cambio. Recuerda por favor poner los issues en el repositorio correcto.  https://github.com/sbohorquez/Econometria2/issues
